name: "Prebuild dev container images"

on:
  push:
    tags:
      - "v*"

jobs:
  prebuild-amc:
    needs: prebuild-latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild amc dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-amc
          imageName: froland/devcontainer-amc
          push: always
          subFolder: src/amc
  prebuild-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild java dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-java
          imageName: froland/devcontainer-java
          push: always
          subFolder: src/java
  prebuild-java-nodejs:
    runs-on: ubuntu-latest
    needs: prebuild-java
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild java-nodejs dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-java-nodejs
          imageName: froland/devcontainer-java-nodejs
          push: always
          subFolder: src/java-nodejs
  prebuild-latex:
    needs: prebuild-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild latex dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-latex
          imageName: froland/devcontainer-latex
          push: always
          subFolder: src/latex
  prebuild-plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild plantuml dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-plantuml
          imageName: froland/devcontainer-plantuml
          push: always
          subFolder: src/plantuml
  prebuild-springboot-react:
    needs: [prebuild-java, prebuild-java-nodejs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild springboot-react dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-springboot-react
          imageName: froland/devcontainer-springboot-react
          push: always
          subFolder: src/springboot-react
  prebuild-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild base devcontainer
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-base
          imageName: froland/devcontainer-base
          push: always
          subFolder: src/base
