name: "Prebuild dev container images"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["java-nodejs", "springboot-react"]
      fail-fast: false
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prebuild ${{ matrix.image }} dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-${{ matrix.image }}
          imageName: froland/devcontainer-${{ matrix.image }}
          push: always
          subFolder: src/${{ matrix.image }}
