name: "Prebuild dev container images"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free more space
        id: free_space
        run: |
          set -e
          # Ensure enough space is available for build
          sudo apt-get autoremove -y
          sudo apt-get clean -y
          sudo rm -rf /usr/share/dotnet
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Prebuild java-nodejs dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-java-nodejs
          imageName: froland/devcontainer-java-nodejs
          imageTag: ${{ steps.meta.outputs.tags }}
          push: always
          subFolder: src/java-nodejs
      - name: Prebuild sprinboog-react dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: froland/devcontainer-springboot-react
          imageName: froland/devcontainer-springboot-react
          imageTag: ${{ steps.meta.outputs.tags }}
          push: always
          subFolder: src/springboot-react
